[general]
seedname = 'lco'
jobname = 'U3.6-ftps-dt0.2-eta0.2'

# solver ftps
# freq range of all objects
w_range = [-10,10]
n_w = 3001
# broadening for k sum and discretization of hyb function
eta=0.2

n_iter_dmft = 1

prec_mu = 0.001
mu_initial_guess = 12.8

h_int_type = 'kanamori'
U = 3.6
J = 0.0

dc_type = 0
dc_dmft = false

h5_save_freq = 1
store_solver = true

[solver]
type = 'ftps'
diag_delta = true
# time step sizes, larger less accurant
dt = 0.2
# automatic bath fit
bath_fit = true
# small bath fit weights are ignored
ignore_weight = 0.1
# where the MPS states are stored, fast r/w important
state_storage = '/tmp/'
# use symmetries of sumk block struc
calc_me = true
# time evo bond dim and cutoff
tw = 1e-10
maxmI = 200
maxmIB = 200
maxmB = 200
# DMRG paramaters
dmrg_tw = 1e-13
sweeps = 12
dmrg_maxmI = 200
dmrg_maxmIB = 200
dmrg_maxmB = 200
